# Generated by Django 2.0.4 on 2018-04-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20180414_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inst',
            old_name='confidance',
            new_name='confidence',
        ),
    ]
